version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:

  build-and-test-frontend:
    executor:
      name: node/default
      tag: '10'
    steps:
      - checkout
      - node/with-cache:
          dir: ~/project/frontend/node_modules
          cache-key: ~/project/frontend/yarn.lock
          steps:
            - run: cd frontend && yarn install
            - run: cd frontend && yarn test
            - run: cd frontend && REACT_APP_BRANCH=$CIRCLE_BRANCH yarn build
      - persist_to_workspace:
          root: frontend
          paths:
            - build

  build-and-test-functions:
    executor:
      name: node/default
      tag: '8'
    steps:
      - checkout
      - restore_cache:
          key: functions-{{ checksum "~/project/functions/package-lock.json" }}
      - run: cd functions && npm install
      - run: cd functions && npm run lint
      - save_cache:
          key: functions-{{ checksum "~/project/functions/package-lock.json" }}
          paths:
            - ~/project/functions/node_modules

  deploy-staging:
    executor:
      name: node/default
      tag: '8'
    steps:
      - checkout
      - attach_workspace:
          at: frontend
      - restore_cache:
          key: functions-{{ checksum "~/project/functions/package-lock.json" }}
      - node/with-cache:
          steps:
            - run: npm install
            - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN -P default

  deploy-production:
    executor:
      name: node/default
      tag: '8'
    steps:
      - checkout
      - attach_workspace:
          at: frontend
      - restore_cache:
          key: functions-{{ checksum "~/project/functions/package-lock.json" }}
      - node/with-cache:
          steps:
            - run: npm install
            - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN -P production

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test-frontend
      - build-and-test-functions
      - deploy-staging:
          requires:
            - build-and-test-frontend
            - build-and-test-functions
          filters:
            branches:
              only: master
      - deploy-production:
          requires:
            - build-and-test-frontend
            - build-and-test-functions
          filters:
            branches:
              only: production
